-- Type of Product --
('NULL', 'Products', 'Agriculture'),
('NULL', 'Products', 'Antiques'),
('NULL', 'Products', 'Appliances'),
('NULL', 'Products', 'Arts & Crafts'),
('NULL', 'Products', 'Audio & Video'),
('NULL', 'Products', 'Automotive Parts'),
('NULL', 'Products', 'Books & Publications'),
('NULL', 'Products', 'Boutiques'),
('NULL', 'Products', 'Cars & Trucks'),
('NULL', 'Products', 'CDs, DVDs, & Blu-rays'),
('NULL', 'Products', 'Chemical'),
('NULL', 'Products', 'Clothing & Accessories'),
('NULL', 'Products', 'Clothing & Fashion'),
('NULL', 'Products', 'Collectibles'),
('NULL', 'Products', 'Computers & IT'),
('NULL', 'Products', 'Construction'),
('NULL', 'Products', 'Cosmetics'),
('NULL', 'Products', 'Dental'),
('NULL', 'Products', 'Electrical'),
('NULL', 'Products', 'Fire Extinguishers'),
('NULL', 'Products', 'Fitness & Health'),
('NULL', 'Products', 'Food & Cookery'),
('NULL', 'Products', 'Food Processing'),
('NULL', 'Products', 'Foods & Beverages'),
('NULL', 'Products', 'Furniture'),
('NULL', 'Products', 'Garden & Nature'),
('NULL', 'Products', 'General Merchandise'),
('NULL', 'Products', 'Glass & Aluminum'),
('NULL', 'Products', 'Groceries'),
('NULL', 'Products', 'Guns & Ammo'),
('NULL', 'Products', 'Hardware'),
('NULL', 'Products', 'Health & Beauty'),
('NULL', 'Products', 'Heavy Equipments'),
('NULL', 'Products', 'Home Design'),
('NULL', 'Products', 'Household & Industrial'),
('NULL', 'Products', 'Imported RTWs'),
('NULL', 'Products', 'Industrial Instruments'),
('NULL', 'Products', 'Medical & Laboratory'),
('NULL', 'Products', 'Musical Instruments'),
('NULL', 'Products', 'Office & School Items'),
('NULL', 'Products', 'Outdoors & Gardens'),
('NULL', 'Products', 'Paints'),
('NULL', 'Products', 'Petroleum & Energy'),
('NULL', 'Products', 'Pets & Grooming'),
('NULL', 'Products', 'Phones & Gadgets'),
('NULL', 'Products', 'Plastic Wares'),
('NULL', 'Products', 'Security & Surveillance'),
('NULL', 'Products', 'Souvenirs & Giveaways'),
('NULL', 'Products', 'Sports & Hobbies'),
('NULL', 'Products', 'Surplus Parts'),
('NULL', 'Products', 'Toys & E-Games'),
('NULL', 'Products', 'Used Cars & Trucks'),
('NULL', 'Products', 'Veterinary'),
('NULL', 'Products', 'Wines & Spirits'),
('NULL', 'Products', 'Other Items'),