-- Type of Service --
('NULL', 'Services', 'Accounting'),
('NULL', 'Services', 'Advertising & Marketing'),
('NULL', 'Services', 'Agriculture & Forestry'),
('NULL', 'Services', 'Animal Welfare'),
('NULL', 'Services', 'Arts & Entertainment'),
('NULL', 'Services', 'Automotive'),
('NULL', 'Services', 'Basic Education'),
('NULL', 'Services', 'Banking & Finance'),
('NULL', 'Services', 'Beauty & Health Salons'),
('NULL', 'Services', 'Brokerage & Investment'),
('NULL', 'Services', 'Casting & Auditions'),
('NULL', 'Services', 'Catering'),
('NULL', 'Services', 'Church & Religion'),
('NULL', 'Services', 'Colleges'),
('NULL', 'Services', 'Computers & Software'),
('NULL', 'Services', 'Consulting'),
('NULL', 'Services', 'Cooperatives & Organizations'),
('NULL', 'Services', 'Courier & Logistics'),
('NULL', 'Services', 'Davao Websites'),
('NULL', 'Services', 'Dental & Optical'),
('NULL', 'Services', 'Electronics Repairs'),
('NULL', 'Services', 'Energy & Environment'),
('NULL', 'Services', 'Engineering'),
('NULL', 'Services', '>Events & Planning'),
('NULL', 'Services', 'Freelancers'),
('NULL', 'Services', 'Funeral & Cemetery'),          
('NULL', 'Services', 'Fabrication & Manufacturing'),
('NULL', 'Services', 'Financial Services'),
('NULL', 'Services', 'Government & Trade'),
('NULL', 'Services', 'Medical & Health'),
('NULL', 'Services', 'Hospitals & Polyclinic'),
('NULL', 'Services', 'Hotels & Apartments'),
('NULL', 'Services', 'Human Resources'),
('NULL', 'Services', 'Employment Agencies'),
('NULL', 'Services', 'Industrial Services'),
('NULL', 'Services', 'IT & Computer Service'),
('NULL', 'Services', 'Internet & Online'),
('NULL', 'Services', 'Laundry Shop'),
('NULL', 'Services', 'Legal Services'),
('NULL', 'Services', 'Malls & Shopping'),
('NULL', 'Services', 'Marketing & Sales'),
('NULL', 'Services', 'Media & Entertainment'),
('NULL', 'Services', 'Preparatory Schools'),
('NULL', 'Services', 'Publishing'),
('NULL', 'Services', 'Pawnshops'),
('NULL', 'Services', 'Pest Control'),
('NULL', 'Services', 'Photography'),
('NULL', 'Services', 'Plants & Factories'),
('NULL', 'Services', 'Printing Press'),
('NULL', 'Services', 'Preparatory Schools'),
('NULL', 'Services', 'Publishing'),
('NULL', 'Services', 'Recreation & Sports'),
('NULL', 'Services', 'Rentals'),
('NULL', 'Services', 'Resorts & Leisure Parks'),
('NULL', 'Services', 'Restaurants'),
('NULL', 'Services', 'Review Centers'),
('NULL', 'Services', 'Rehabilitation Centers'),
('NULL', 'Services', 'Real Estate & Construction'),
('NULL', 'Services', 'Rental Service'),
('NULL', 'Services', 'Repairs & Maintenance'),
('NULL', 'Services', 'Retail & Consumer Services'),
('NULL', 'Services', 'Safety Consultants'),
('NULL', 'Services', 'Supermarkets'),
('NULL', 'Services', 'Security & Detective Agencies'),
('NULL', 'Services', 'Small Businesses'),
('NULL', 'Services', 'Tailoring & Clothing'),
('NULL', 'Services', 'Textile Printers'),
('NULL', 'Services', 'Tutorials'),
('NULL', 'Services', 'Telecommunications'),
('NULL', 'Services', 'Transportation & Logistics'),
('NULL', 'Services', 'Travel & Tourism'),
('NULL', 'Services', 'Universities'),
('NULL', 'Services', 'Veterinary'),
('NULL', 'Services', 'Vocational Schools'),
('NULL', 'Services', 'Warehousing'),
('NULL', 'Services', 'Water Refilling'),
('NULL', 'Services', 'Web Design & Hosting'),
('NULL', 'Services', 'Wedding & Receptions'),